name: Build and Sign APK with Cordova

on:
  workflow_dispatch:
    inputs:
      html:
        description: 'Contenido HTML con CSS y JS embebidos'
        required: true
        type: string
      app_name:
        description: 'Nombre de la aplicación'
        required: false
        default: 'MiAplicacion'
        type: string
      package_name:
        description: 'Nombre del paquete'
        required: false
        default: 'com.example.miaplicacion'
        type: string
      android_target:
        description: 'Versión del SDK objetivo de Android'
        required: false
        default: '33'
        type: string

env:
  NODE_VERSION: '20.11.1'
  JAVA_VERSION: '17.0.10'
  ANDROID_SDK_VERSION: '33'
  GRADLE_VERSION: '8.0.2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Configurar el SDK de Android
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_SDK_VERSION }}
          accept-licenses: true

      - name: Instalar herramientas de compilación de Android
        run: |
          echo "Instalando herramientas de compilación de Android..."
          yes | sdkmanager "platforms;android-${{ env.ANDROID_SDK_VERSION }}" "build-tools;${{ env.ANDROID_SDK_VERSION }}" --licenses

      - name: Instalar Gradle
        run: |
          echo "Instalando Gradle..."
          wget https://services.gradle.org/distributions/gradle-${{ env.GRADLE_VERSION }}-bin.zip
          unzip gradle-${{ env.GRADLE_VERSION }}-bin.zip
          export PATH=$PATH:$PWD/gradle-${{ env.GRADLE_VERSION }}/bin
          gradle --version

      - name: Instalar Cordova y dependencias globales
        run: |
          echo "Instalando Cordova y dependencias globales..."
          npm install -g cordova@latest native-run@latest cordova-res@latest
          cordova --version

      - name: Crear y preparar proyecto Cordova
        run: |
          echo "Creando proyecto Cordova..."
          cordova create "${{ github.event.inputs.app_name }}" "${{ github.event.inputs.package_name }}" "${{ github.event.inputs.app_name }}"
          cd "${{ github.event.inputs.app_name }}"
          echo "Agregando plataforma Android..."
          cordova platform add android@latest --verbose
          echo "Copiando contenido HTML proporcionado..."
          echo "${{ github.event.inputs.html }}" > www/index.html
          echo "Instalando dependencias del proyecto..."
          npm install

      - name: Configurar Gradle
        run: |
          cd "${{ github.event.inputs.app_name }}"
          echo "Configurando Gradle..."
          mkdir -p platforms/android/gradle/wrapper
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-${{ env.GRADLE_VERSION }}-bin.zip" > platforms/android/gradle/wrapper/gradle-wrapper.properties
          chmod +x platforms/android/gradlew

      - name: Construir APK
        run: |
          cd "${{ github.event.inputs.app_name }}"
          echo "Limpiando y construyendo el proyecto..."
          ./platforms/android/gradlew clean --stacktrace
          cordova build android --release --verbose -- --stacktrace
        env:
          JAVA_OPTS: '-Xmx4g'

      - name: Configurar keystore
        run: |
          cd "${{ github.event.inputs.app_name }}"
          echo "Configurando keystore..."
          echo "${{ secrets.KEYSTORE }}" | base64 -d > my-release-key.jks
          if [ ! -f my-release-key.jks ]; then
            echo "Error: No se pudo crear el archivo keystore"
            exit 1
          fi

      - name: Firmar y alinear APK
        run: |
          cd "${{ github.event.inputs.app_name }}"
          APK_PATH=$(find platforms/android/app/build/outputs/apk/release -name "*.apk" -type f | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "Error: No se encontró el APK"
            exit 1
          fi
          echo "Firmando APK..."
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore my-release-key.jks -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -keypass "${{ secrets.KEY_PASSWORD }}" "$APK_PATH" "${{ secrets.KEY_ALIAS }}"
          SIGNED_APK="app-release-signed.apk"
          echo "Alineando APK..."
          ${ANDROID_HOME}/build-tools/${{ env.ANDROID_SDK_VERSION }}/zipalign -v 4 "$APK_PATH" "$SIGNED_APK"
          echo "Verificando APK alineado..."
          ${ANDROID_HOME}/build-tools/${{ env.ANDROID_SDK_VERSION }}/apksigner verify --verbose "$SIGNED_APK"

      - name: Subir APK firmada
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: ${{ github.event.inputs.app_name }}/app-release-signed.apk
          retention-days: 7
