name: Build Debug APK with Capacitor
on:
  workflow_dispatch:
    inputs:
      html:
        description: 'HTML content with embedded CSS and JS'
        required: true
        type: string
      app_name:
        description: 'Application name'
        required: false
        default: '3EnRaya'
        type: string
      package_name:
        description: 'Package name'
        required: false
        default: 'com.example.tresenraya'
        type: string

env:
  NODE_VERSION: '20.11.1'
  JAVA_VERSION: '17.0.10'
  ANDROID_SDK_VERSION: '33'
  GRADLE_VERSION: '8.0.2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Create base project structure
        run: |
          # Crear package.json
          echo '{
            "name": "html-to-apk-converter",
            "version": "1.0.0",
            "description": "Converts HTML into APK using Capacitor",
            "main": "index.js",
            "scripts": {
              "build": "echo \"No build step required\"",
              "cap.add": "cap add android",
              "cap.build": "cd android && ./gradlew assembleDebug --stacktrace"
            },
            "dependencies": {
              "@capacitor/android": "^5.7.0",
              "@capacitor/core": "^5.7.0"
            },
            "devDependencies": {
              "@capacitor/cli": "^5.7.0"
            },
            "author": "",
            "license": "MIT"
          }' > package.json
          
          # Instalar dependencias
          npm install

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_SDK_VERSION }}
          accept-licenses: true

      - name: Install Android build tools
        run: |
          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true
          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "platforms;android-${{ env.ANDROID_SDK_VERSION }}" "build-tools;${{ env.ANDROID_SDK_VERSION }}.0.0"

      - name: Setup Capacitor project
        run: |
          # Crear directorio www
          mkdir -p www
          
          # Crear index.html con el contenido HTML proporcionado
          echo '${{ github.event.inputs.html }}' | base64 --decode > www/index.html || echo '${{ github.event.inputs.html }}' > www/index.html
          
          # Inicializar proyecto de Capacitor
          npx cap init "${{ github.event.inputs.app_name }}" "${{ github.event.inputs.package_name }}" --web-dir="www"
          
          # Crear capacitor.config.json con configuraciones adicionales
          echo '{
            "appId": "${{ github.event.inputs.package_name }}",
            "appName": "${{ github.event.inputs.app_name }}",
            "webDir": "www",
            "bundledWebRuntime": false,
            "server": {
              "androidScheme": "http",
              "cleartext": true
            },
            "android": {
              "buildOptions": {
                "keystorePath": "release.keystore",
                "keystorePassword": "android",
                "keystoreAlias": "androidalias",
                "keystoreAliasPassword": "android"
              }
            }
          }' > capacitor.config.json
          
          # Eliminar el directorio android si existe
          rm -rf android
          
          # Agregar plataforma Android
          npx cap add android
          
          # Sincronizar configuración de Android
          npx cap sync android

      - name: Build debug APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug --stacktrace

      - name: Comprimir proyecto de Android Studio
        run: |
          zip -r android_project.zip android/

      - name: Upload debug APK and Android project
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
            android_project.zip
          retention-days: 7
