name: Build APK
on:
  workflow_dispatch:
    inputs:
      html:
        description: 'HTML content'
        required: true
      css:
        description: 'CSS content'
        required: false
      js:
        description: 'JavaScript content'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Android project
        run: |
          # Crear estructura del proyecto
          mkdir -p AndroidApp/app/src/main/assets
          mkdir -p AndroidApp/app/src/main/java/com/webview/app
          mkdir -p AndroidApp/app/src/main/res/layout
          mkdir -p AndroidApp/app/src/main/res/values

          # Crear archivos web
          echo "${{ github.event.inputs.html }}" > AndroidApp/app/src/main/assets/index.html
          echo "${{ github.event.inputs.css }}" > AndroidApp/app/src/main/assets/styles.css
          echo "${{ github.event.inputs.js }}" > AndroidApp/app/src/main/assets/script.js

          # Crear build.gradle raíz usando la nueva sintaxis
          cat > AndroidApp/build.gradle << 'EOL'
          plugins {
              id 'com.android.application' version '8.1.0' apply false
          }
          EOL

          # Crear settings.gradle con los repositorios necesarios
          cat > AndroidApp/settings.gradle << 'EOL'
          pluginManagement {
              repositories {
                  google()
                  mavenCentral()
                  gradlePluginPortal()
              }
          }
          dependencyResolutionManagement {
              repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
              repositories {
                  google()
                  mavenCentral()
              }
          }
          rootProject.name = 'AndroidApp'
          include ':app'
          EOL

          # Crear build.gradle del módulo app con configuración actualizada
          cat > AndroidApp/app/build.gradle << 'EOL'
          plugins {
              id 'com.android.application'
          }

          android {
              namespace 'com.webview.app'
              compileSdk 34

              defaultConfig {
                  applicationId "com.webview.app"
                  minSdk 24
                  targetSdk 34
                  versionCode 1
                  versionName "1.0"
              }

              buildTypes {
                  release {
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
          }

          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation 'com.google.android.material:material:1.11.0'
          }
          EOL

          # Crear MainActivity
          cat > AndroidApp/app/src/main/java/com/webview/app/MainActivity.java << 'EOL'
          package com.webview.app;

          import android.os.Bundle;
          import android.webkit.WebView;
          import android.webkit.WebViewClient;
          import androidx.appcompat.app.AppCompatActivity;

          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  WebView webView = new WebView(this);
                  webView.getSettings().setJavaScriptEnabled(true);
                  webView.setWebViewClient(new WebViewClient());
                  setContentView(webView);
                  webView.loadUrl("file:///android_asset/index.html");
              }
          }
          EOL

          # Crear AndroidManifest.xml
          cat > AndroidApp/app/src/main/AndroidManifest.xml << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="Web App"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOL

          # Crear archivo de recursos
          cat > AndroidApp/app/src/main/res/values/styles.xml << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
              </style>
          </resources>
          EOL

      - name: Setup Gradle Wrapper
        run: |
          cd AndroidApp
          gradle wrapper
          chmod +x gradlew

      - name: Build APK
        working-directory: AndroidApp
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: AndroidApp/app/build/outputs/apk/debug/app-debug.apk
