name: Build Android Studio Project

on:
  workflow_dispatch:
    inputs:
      html:
        description: 'HTML file content'
        required: true
      css:
        description: 'CSS file content'
        required: false
      js:
        description: 'JS file content'
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova project
      run: |
        cordova create app com.example.app App
        cd app
        cordova platform add android

    - name: Copy files
      run: |
        mkdir -p app/www
        echo "${{ github.event.inputs.html }}" > app/www/index.html
        if [ -n "${{ github.event.inputs.css }}" ]; then
          echo "${{ github.event.inputs.css }}" > app/www/styles.css
        fi
        if [ -n "${{ github.event.inputs.js }}" ]; then
          echo "${{ github.event.inputs.js }}" > app/www/script.js
        fi
        cd app

    - name: Prepare Android project
      run: |
        cd app
        cordova prepare android

    - name: Fix Android project structure for Android Studio
      run: |
        cd app/platforms/android
        mkdir -p app/src/main/assets/www
        cp -r ../../../app/www/* app/src/main/assets/www/
        rm -rf cordova
        rm -rf CordovaLib

    - name: Build APK
      run: |
        cd app
        cordova build android --release

    - name: Create output folders
      run: |
        mkdir -p output/Aquí_está_tu_APK
        mkdir -p output/Tu_APK_para_modificar

    - name: Copy APK to output folder
      run: |
        cp app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk output/Aquí_está_tu_APK/

    - name: Copy Android Studio project to output folder
      run: |
        cp -r app/platforms/android/* output/Tu_APK_para_modificar/

    - name: Zip output folders
      run: |
        cd output
        zip -r ../android-studio-project.zip ./*

    - name: Upload Android Studio project as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-studio-project.zip
        path: android-studio-project.zip
