name: Build and Sign APK with Cordova

on:
  workflow_dispatch:
    inputs:
      html:
        description: 'Contenido HTML con CSS y JS embebidos'
        required: true
        type: string
      app_name:
        description: 'Nombre de la aplicación'
        required: false
        default: 'MiAplicacion'
        type: string
      package_name:
        description: 'Nombre del paquete'
        required: false
        default: 'com.example.miaplicacion'
        type: string
      android_target:
        description: 'Versión del SDK objetivo de Android'
        required: false
        default: '33'
        type: string

env:
  NODE_VERSION: '20.11.1'
  JAVA_VERSION: '17.0.10'
  ANDROID_SDK_VERSION: '33'
  GRADLE_VERSION: '8.0.2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Configurar el SDK de Android
        uses: android-actions/setup-android@v3
        with:
          android-sdk: ${{ env.ANDROID_SDK_VERSION }}
          accept-licenses: true

      - name: Instalar la plataforma del SDK de Android
        run: |
          echo "Instalando la plataforma del SDK de Android (android-${{ env.ANDROID_SDK_VERSION }})..."
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "platforms;android-${{ env.ANDROID_SDK_VERSION }}"

      - name: Instalar Cordova y dependencias globales
        run: |
          npm install -g cordova@latest native-run@latest cordova-res@latest
          cordova --version

      - name: Preparar proyecto Cordova
        run: |
          # Crear el proyecto Cordova
          cordova create "${{ github.event.inputs.app_name || 'MiAplicacion' }}" \
            "${{ github.event.inputs.package_name || 'com.example.miaplicacion' }}" \
            "${{ github.event.inputs.app_name || 'MiAplicacion' }}"
          
          # Cambiar al directorio del proyecto
          cd "${{ github.event.inputs.app_name || 'MiAplicacion' }}"
          
          # Agregar la plataforma Android
          echo "Agregando plataforma Android..."
          cordova platform add android@latest
          
          # Verificar que la plataforma se agregó correctamente
          if [ ! -d platforms/android ]; then
            echo "Error: La plataforma Android no se agregó correctamente"
            exit 1
          fi

          # Verificar que gradlew existe
          if [ ! -f platforms/android/gradlew ]; then
            echo "Error: No se encontró el archivo gradlew"
            ls -la platforms/android/
            exit 1
          fi
          
          # Dar permisos de ejecución a gradlew
          chmod +x platforms/android/gradlew
          
          # Verificar requisitos
          cordova requirements

      - name: Configurar ajustes del proyecto
        run: |
          cd "${{ github.event.inputs.app_name || 'MiAplicacion' }}"
          
          # Actualizar config.xml
          sed -i "s/<platform name=\"android\">/<platform name=\"android\">\n        <preference name=\"android-targetSdkVersion\" value=\"${{ github.event.inputs.android_target }}\"\/>/g" config.xml
          sed -i "/<platform name=\"android\">/a \        <preference name=\"AndroidXEnabled\" value=\"true\"\/>" config.xml

          # Configurar gradle-wrapper.properties
          mkdir -p platforms/android/gradle/wrapper
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-${{ env.GRADLE_VERSION }}-bin.zip" > platforms/android/gradle/wrapper/gradle-wrapper.properties

      - name: Construir APK
        run: |
          cd "${{ github.event.inputs.app_name || 'MiAplicacion' }}"
          # Limpiar primero
          ./platforms/android/gradlew clean --stacktrace
          # Construir APK
          cordova build android --release --verbose -- --stacktrace
        env:
          JAVA_OPTS: '-Xmx4g'

      - name: Configurar y firmar APK
        run: |
          cd "${{ github.event.inputs.app_name || 'MiAplicacion' }}"
          # Configurar keystore
          if [ -z "${{ secrets.KEYSTORE }}" ]; then
            echo "Error: El secreto KEYSTORE no está configurado"
            exit 1
          fi
          echo "${{ secrets.KEYSTORE }}" | base64 -d > my-release-key.jks
          
          # Encontrar y firmar APK
          APK_PATH=$(find platforms/android/app/build/outputs/apk/release -name "*.apk" -type f | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "Error: No se encontró el APK"
            exit 1
          fi
          
          echo "APK encontrado en: $APK_PATH"
          
          # Firmar APK
          jarsigner -verbose \
            -sigalg SHA256withRSA \
            -digestalg SHA-256 \
            -keystore my-release-key.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            "$APK_PATH" \
            "${{ secrets.KEY_ALIAS || 'alias_name' }}"
          
          # Alinear y verificar
          SIGNED_APK="app-release-signed.apk"
          ${ANDROID_HOME}/build-tools/$(ls ${ANDROID_HOME}/build-tools | sort -V | tail -1)/zipalign -v 4 "$APK_PATH" "$SIGNED_APK"
          ${ANDROID_HOME}/build-tools/$(ls ${ANDROID_HOME}/build-tools | sort -V | tail -1)/apksigner verify --verbose "$SIGNED_APK"

      - name: Subir APK firmada
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: ${{ github.event.inputs.app_name || 'MiAplicacion' }}/app-release-signed.apk
          retention-days: 7
