name: Build Android Studio Project

on:
  workflow_dispatch:
    inputs:
      html:
        description: 'HTML file content'
        required: true
      css:
        description: 'CSS file content'
        required: false
      js:
        description: 'JS file content'
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova project
      run: |
        cordova create app com.example.app App
        cd app
        cordova platform add android

    - name: Copy files
      run: |
        echo "${{ github.event.inputs.html }}" > app/www/index.html
        echo "${{ github.event.inputs.css }}" > app/www/styles.css
        echo "${{ github.event.inputs.js }}" > app/www/script.js
        cd app

    - name: Prepare Android project
      run: |
        cd app
        cordova prepare android

    - name: Zip Android Studio project
      run: |
        cd app/platforms/android
        zip -r ../../../android-studio-project.zip ./*

    - name: Upload Android Studio project as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-studio-project.zip
        path: android-studio-project.zip
