name: Build APK

on:
  workflow_dispatch: # Permite ejecutar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova project
      run: |
        cordova create app com.example.app App
        cd app
        cordova platform add android

    - name: Copy files
      run: |
        cp -r ../public/* www/
        cd ..

    - name: Build APK
      run: |
        cd app
        cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/platforms/android/app/build/outputs/apk/debug/app-debug.apk