name: Build APK
on:
  workflow_dispatch:
    inputs:
      html:
        description: 'HTML content'
        required: true
      css:
        description: 'CSS content'
        required: false
      js:
        description: 'JavaScript content'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Android project
        run: |
          mkdir -p AndroidApp/app/src/main/{assets,java/com/webview/app,res/layout,res/values}

          # Crear archivos web
          echo "${{ github.event.inputs.html }}" > AndroidApp/app/src/main/assets/index.html
          echo "${{ github.event.inputs.css }}" > AndroidApp/app/src/main/assets/styles.css
          echo "${{ github.event.inputs.js }}" > AndroidApp/app/src/main/assets/script.js

          # settings.gradle.kts
          cat > AndroidApp/settings.gradle.kts << 'EOL'
          rootProject.name = "AndroidApp"
          include(":app")
          EOL

          # build.gradle.kts del proyecto
          cat > AndroidApp/build.gradle.kts << 'EOL'
          buildscript {
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath("com.android.tools.build:gradle:8.2.0")
              }
          }

          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          EOL

          # build.gradle.kts de la app
          cat > AndroidApp/app/build.gradle.kts << 'EOL'
          plugins {
              id("com.android.application")
          }

          android {
              namespace = "com.webview.app"
              compileSdk = 34
              
              defaultConfig {
                  applicationId = "com.webview.app"
                  minSdk = 21
                  targetSdk = 34
                  versionCode = 1
                  versionName = "1.0"
              }
              
              buildTypes {
                  release {
                      isMinifyEnabled = false
                      proguardFiles(
                          getDefaultProguardFile("proguard-android-optimize.txt"),
                          "proguard-rules.pro"
                      )
                  }
              }
              
              compileOptions {
                  sourceCompatibility = JavaVersion.VERSION_17
                  targetCompatibility = JavaVersion.VERSION_17
              }
          }

          dependencies {
              implementation("androidx.appcompat:appcompat:1.6.1")
              implementation("androidx.core:core-ktx:1.12.0")
          }

          repositories {
              google()
              mavenCentral()
          }
          EOL

          # MainActivity.java
          cat > AndroidApp/app/src/main/java/com/webview/app/MainActivity.java << 'EOL'
          package com.webview.app;

          import android.os.Bundle;
          import android.webkit.WebView;
          import android.webkit.WebViewClient;
          import androidx.appcompat.app.AppCompatActivity;

          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  WebView webView = new WebView(this);
                  webView.getSettings().setJavaScriptEnabled(true);
                  webView.setWebViewClient(new WebViewClient());
                  setContentView(webView);
                  webView.loadUrl("file:///android_asset/index.html");
              }
          }
          EOL

          # AndroidManifest.xml
          cat > AndroidApp/app/src/main/AndroidManifest.xml << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <application
                  android:allowBackup="true"
                  android:label="Web App"
                  android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOL

          # styles.xml
          cat > AndroidApp/app/src/main/res/values/styles.xml << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar" />
          </resources>
          EOL

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Build Debug APK
        run: |
          cd AndroidApp
          gradle assembleDebug --warning-mode all

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: AndroidApp/app/build/outputs/apk/debug/app-debug.apk
